version: '3.8'

services:
  database:
    container_name: PostgresDb
    image: 'postgres:14'
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/db
    networks:
      - spring-network

volumes:
  db-data:

networks:
  spring-network:
    driver: bridge